name: 'Deployment to Develop'

on:
  push:
    branches:
      - master

jobs:
  depl-develop:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
      - name: Build the docker-compose stack
        run: docker-compose up --build -d dev
      - name: Check running containers
        run: docker ps -a
