name: release-please
on:
  # !STARTERCONF Choose your preferred event
  # !Option 1: Manual Trigger from GitHub
  workflow_dispatch:
  # !Option 2: Release on every push on main branch
  # push:
  #   branches:
  #     - main

jobs:
  release-please:
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.TOKEN }}
          release-type: node
          package-name: release-please-action

      - uses: actions/checkout@v1
        with:
          ref: release-please--branches--main--components--release-please-action
      - name: Build the docker-compose stack
        run: docker-compose up --build -d web
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker logs app-store-front
      # - name: Run test suite
      #   run: docker exec app-store-front pytest --skip-auth
